# Generated by Django 5.2.7 on 2025-10-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
